dist: focal
language: cpp
addons:
  apt:
    packages:
      - build-essential
      - libopencv-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - echo "C++ tests"
  - build/seam_carving_test
  - build/content_aware_image_resize -s buffalo.jpg
